name = "experiments"
compatibility_date = "2024-01-01"

[build]
command = "yarn install --frozen-lockfile=false && yarn build"
output_dir = ".next"

[build.environment]
YARN_ENABLE_SCRIPTS = "true"
YARN_ENABLE_GLOBAL_CACHE = "true"
NODE_VERSION = "20.14.0"